### PR TITLE
docs: add LICENSE file (MIT)

### PR DESCRIPTION
**Pull request by darcien**

### CODE REVIEW

**Comment by oshimayoan** [comment]
We only need one on the root? Does it includes everything inside `packages` directory?

**Comment by sstur** [comment]
Yes, I'm fine with just one in the root. But make sure that all the package.json files _if_ they have a license field that it matches this one (BSD). Thanks!

**Comment by darcien** [comment]
> 
> 
> Yes, I'm fine with just one in the root. But make sure that all the package.json files _if_ they have a license field that it matches this one (BSD). Thanks!

Actually, the license file in this PR is MIT, do you want to change it to the equivalent BSD like BSD 2, or BSD 3?

**Comment by sstur** [comment]
Oops, I didn't read that carefully enough. I don't have a strong preference, so long as we're consistent.

**Pull request merged**
