### PR TITLE
feat(exoflex): add `testID` to some components

### LINKED ISSUE #384: exoflex: testID not found from props
**Describe the problem**
Every component should have a prop called `testID` for testing purpose but it can't be found in several exoflex's components.

**Expected behavior**
Every component should have the prop that will pass it into the inner component so the user can access that component through testing.

### PR DESCRIPTION
**Pull request by oshimayoan**
Resolves #384. 

Honestly, I'm still not sure if it's the best solution for `RichRadioButton` component.

### CODE REVIEW

**Comment by darcien** [comment]
> Honestly, I'm still not sure if it's the best solution for `RichRadioButton` component.

Looks fine to me, what's your concern?

**Comment by oshimayoan** [comment]
Well, because I put the `testID` inside the `data` object.

**Comment by darcien** [comment]
> Well, because I put the `testID` inside the `data` object.

Ahh right, but in #409 we separated the Item and the Group right, so we don't have to pass the `testID` together with the data.

**Comment by oshimayoan** [comment]
Yeah, that's true tho. I guess we could land this now.

**Pull request merged**
